// <auto-generated />
using MTCCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MTCCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260219132716_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("MTCCore.Domain.Entities.GroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FF0000",
                            GroupName = "None"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#00FF00",
                            GroupName = "Група 1"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#0000FF",
                            GroupName = "Група 2"
                        });
                });

            modelBuilder.Entity("MTCCore.Domain.Entities.NodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Distance")
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupEnttityId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeIdentity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NodeUniqueId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupEnttityId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("MTCCore.Domain.Entities.PositionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("NodeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NodeId")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("MTCCore.Domain.Entities.TimeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupEntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Time")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupEntityId");

                    b.ToTable("Time");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GroupEntityId = 1,
                            Time = "00:05"
                        },
                        new
                        {
                            Id = 2,
                            GroupEntityId = 1,
                            Time = "00:10"
                        },
                        new
                        {
                            Id = 3,
                            GroupEntityId = 2,
                            Time = "00:15"
                        },
                        new
                        {
                            Id = 4,
                            GroupEntityId = 2,
                            Time = "00:20"
                        });
                });

            modelBuilder.Entity("MTCCore.Domain.Entities.NodeEntity", b =>
                {
                    b.HasOne("MTCCore.Domain.Entities.GroupEntity", "GroupEnttity")
                        .WithMany("Nodes")
                        .HasForeignKey("GroupEnttityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupEnttity");
                });

            modelBuilder.Entity("MTCCore.Domain.Entities.PositionEntity", b =>
                {
                    b.HasOne("MTCCore.Domain.Entities.NodeEntity", "Node")
                        .WithOne("Position")
                        .HasForeignKey("MTCCore.Domain.Entities.PositionEntity", "NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Node");
                });

            modelBuilder.Entity("MTCCore.Domain.Entities.TimeEntity", b =>
                {
                    b.HasOne("MTCCore.Domain.Entities.GroupEntity", "GroupEntity")
                        .WithMany("Times")
                        .HasForeignKey("GroupEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupEntity");
                });

            modelBuilder.Entity("MTCCore.Domain.Entities.GroupEntity", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("Times");
                });

            modelBuilder.Entity("MTCCore.Domain.Entities.NodeEntity", b =>
                {
                    b.Navigation("Position");
                });
#pragma warning restore 612, 618
        }
    }
}
